### ISSUE TITLE
[EPIC]: A modern and compliant web app to display the AI generated data

### ISSUE THREAD

**Issue by Mexmorize** [PHACDataHub/project-intake#17]
### 👱 Suggester Name

Ben Butmir

### 🎯 Milestone

M8 - Deploy PBMM-ready Cloud Infrastructure for Public Health Intelligence (CIPHI)

### ❓ Problem Statement

We currently don't have any modern web application that displays AI generated metrics within a PBMM environment.

### 🎉Desired Outcome Summary

We would have a modern full-stack application that can query a GraphQL backend to display AI computed data

### 📋 Detailed Description

An accessibility friendly and modern front-end like Chakra/React. We could use something like Docker to containerize the application and lean more towards to the microservices framework and Kubernetes. We can look into Django into the main controller since it's currently being used within PHAC and is somewhat modern. I think it would be good to have something like a PostgreSQL back-end and pgAdmin interface which is fed through an Apollo GraphQL API to the front-end.

### ✔️ Feature List

- [ ] A modern and accessibility compliant front-end such as Chakra and React
- [ ] A PostGreSQL database
- [ ] An Apollo GraphQL API
- [ ] Django controller to connect all the pieces
- [ ] Docker to containerize the application
- [ ] Kubernetes in GCP to deploy the web application
