### ISSUE TITLE
[EPIC]: Data governance document that details all the metrics that Canadians and epidemiologists would deem valuable

### ISSUE THREAD

**Issue by Mexmorize** [PHACDataHub/project-intake#18]
### 👱 Suggester Name

Ben Butmir

### 🎯 Milestone

M8 - Deploy PBMM-ready Cloud Infrastructure for Public Health Intelligence (CIPHI)

### ❓ Problem Statement

We currently do not know what metrics would be useful for Canadians to know about public health.

### 🎉Desired Outcome Summary

We would now have a document outlining the relevant information and metrics that experts and Canadians would deem valuable to know

### 📋 Detailed Description

Since we need to display the health of Canadians through a dashboard, we will need to discuss and engage with experts and Canadians about what metrics they think are important and would deem valuable. After the engagement, we will need to document some information about the findings and discuss it with internal partners about what datasets/sources are currently available. When this list is complete (maybe with the data catalogue) we can hand off this information to the development/data science team(s) to action and put into the web application.

### ✔️ Feature List

- [ ] An engagement with experts about relevant data and metrics to display
- [ ] An engagement with Canadians about relevant data and metrics to display
- [ ] A search of what datasets we currently have access to
- [ ] A final report to present and/or provide the development team to action and put within the web application

**Comment by tomcdona** [comment]
@Mexmorize this is starting to look pretty decent, I think it's time for another chat about all this.
@KingBain there's a bunch of different 'intake/project onboarding/etc' things happening. GitHub Issues may not be a source-of-truth for project/portfolio mgmt at the branch level...let's keep this theoretical for now please
