### ISSUE TITLE
[EPIC]: Project Intake Process

### ISSUE THREAD

**Issue by Mexmorize** [PHACDataHub/project-intake#20]
### 👱 Suggester Name

Ben Butmir

### 🎯 Milestone

M1 - Establish a governance Secretariat

### ❓ Problem Statement

Currently no process in place for this.

### 🎉Desired Outcome Summary

We have a process to better reflect our work and upscale reporting

### 📋 Detailed Description

To create a process that helps lead and start the technical conversation after it has been assigned/given to DE. This involves a process diagram with some feedback loop, 

- Provide information about what we offer
- Ability to triage requests
- Feedback loop / mechanism to see if we have enough technical information
- Linkages with master project in MS list / master excel project list (project id/key)
- 

### ✔️ Feature List

- [ ] Create a service catalogue
- [ ] Finalize the workflow diagram around how we take in projects 
> Feedback loop / mechanism to see if we have enough technical information
> Allow the client / product owner to review the project and provide feedback
- [ ] Determine how this would link with master project in MS list / master excel project list (project id/key)
