### ISSUE TITLE
[EPIC]: Self-serve intake process

### ISSUE THREAD

**Issue by tcaky** [PHACDataHub/project-intake#21]
### 👱 Suggester Name

Keith Young

### 🎯 Milestone

M1 - Establish a governance Secretariat

### ❓ Problem Statement

No process exists to fast-track simple (templated) onboarding

### 🎉Desired Outcome Summary

A process to allow fast technology delivery with minimal or no human interaction

### 📋 Detailed Description

We don't have a process to allow users to self-serve simple technology requests.

A simple use-case would be, "I am a data scientist and I need to process data over the next 72 hours".

We should have an intake form that allows a user to select from pre-defined templates with known boundaries (compute limits, time limits).  They fill out the form, and a few automatic checks are done and the successful path in the use-case means the resources are spun-up and the user receives an email indicating their resources are ready for use.

### ✔️ Feature List

- [ ] Come up with process flow that represents this process
- [ ] Come up with template ideas for commodity simple use-cases
- [ ] Decide what the minimum viable form requirements are

> If a new GCP identity is needed how is the automation flow impacted and resolved?
