### ISSUE TITLE
[EPIC]: Create reusable web-platform

### ISSUE THREAD

**Issue by GRaganold** [PHACDataHub/project-intake#22]
### 👱 Suggester Name

Geordin Raganold

### 🎯 Milestone

M5 - Deploy an interoperability (API) platform

### ❓ Problem Statement

Currently many teams developing projects without standardization 

### 🎉Desired Outcome Summary

 Reusable web-app that could be deployed on the cloud with API compatibility 

### 📋 Detailed Description

Reusable web-app that could be deployed on the cloud with API compatibility utilizing GraphQL, PostgreSQL, Django, PG Admin, Docker and React.

This will allow team with the intent to develop an internal web app to create one from a developed starting point with standardization, an API, and functionality out of the box.

This will increase/speed up development time drastically and build toward the desired reusable data mesh future state.

Once developed, the project will be migrated to the cloud using k8's and pull the infrastructure as code script to allow automated deployment for clients to use in future

### ✔️ Feature List

- [ ] Local Docker Django container that controls the GraphQL API.
- [ ] Local Docker PG Admin container that has a GUI for the PostgreSQL database.
- [ ] Local Docker PostgreSQL container that stores the data.
- [ ] Local Docker React frontend container which displays an analytics dashboard from the metrics fetched from the API.
- [ ] Deployed Google Cloud Platform (GCP) version of the local application.
- [ ] Automated infrastructure as code deployment script.
- [ ] Documentations for the platform.
- [ ] CI/CD and quality of life GitHub Actions.
