### ISSUE TITLE
[EPIC]: Create Web app

### ISSUE THREAD

**Issue by Mexmorize** [PHACDataHub/project-intake#6]
### 👱 Suggester Name

Ben Butmir

### 🎯 Milestone

M4 - Develop a Cloud Adoption Framework

### ❓ Problem Statement

We currently don't have any that meet our needs for the client

### 🎉Desired Outcome Summary

Having a web application with a graphQL backend to query

### 📋 Detailed Description

Something more here

### ✔️ Feature List

- [ ] log in and log out
- [ ] Authentications
- [ ] Dashboard with analytics
- [ ] Deploy to cloud
